### ISSUE TITLE
Провести переименование сишных функций (и файлов) чтобы убрать конфликты линковщика с обычным криптонитом.

### ISSUE THREAD

**Issue by ivanovs-4** [hexresearch/ed25519-keccak#1]
s/cryptonite/cryptonite_kc_/ внутри cbits
переименоваать по необходимости файлы
наладить чтобы компилировалось

**Comment by ArthurVard** [comment]
**Вопроси на понимание:**

1.  конфликт создают `с`-ишние функции при линковке, т.к. они по сигнатуре идентичны с функциями в пакете криптоните и линковщик путает как то
2. у нас изменено всего 4 функции - 
```
static void ed25519_hash_init(..)
static void ed25519_hash_update(..)
static void ed25519_hash_final(..)
static void ed25519_hash(..)
```

если переименовать эти функции везде то в принципе должно работать, если (1) суждение правильное
3. от пакета "`ed25519-keccak`" экспортируется модуле "`Crypto.NemEd2551`9", я нигде не нашел его импорт, но пакет используется в проектах
```
 - xenochain-mock/stack.yaml
 - xenogate/stack.yaml
 - xenochain-service/stack.yaml
 - xenochain-types/xenochain-types.cabal
```
  как (какой импорт) и где (какие функции) мы используем пакет `"ed25519-keccak"`

4.` s/cryptonite/cryptonite_kc_/ внутри cbits` - как поинимать?

**Comment by ivanovs-4** [comment]
1. Правильно
2. На данный момент может быть будет достаточно переименовать только эти функции (и те, которые их используют, и так далее вверх все зависимые), но на будущее может потребоваться переименовать все функции потому что в других версиях криптонита они могут тоже поменяться (теоретически), и тоже создавать конфликты.
3. Он импортироуется в проекте https://github.com/hexresearch/bc-api/blob/master/nem-api/package.yaml#L69, который используется в гейте.
4. `s/cryptonite/cryptonite_kc_/ ` - это как в команде `sed`: поменять все строки `cryptonite` на `cryptonite_kc_`

**Comment by ArthurVard** [comment]
failure <https://drone1.hxr.team/hexresearch/xenochain/233> (kh/crypto-test)『Тест для проблем с keccak

Для проверки следует собрать xenogate и запустить в норме программа
должна выводить:

> True
> True

Если закомментировать runMainGateNode так и будет. Если не комментировать
будет выводиться False』by Shimuuar
